export const seats = [
  {
    id: 1,
    rowNumber: 1,
    seatNumber: 1,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 82,
    rowNumber: 1,
    seatNumber: 1,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 2,
    rowNumber: 1,
    seatNumber: 2,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 83,
    rowNumber: 1,
    seatNumber: 2,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 3,
    rowNumber: 1,
    seatNumber: 3,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 84,
    rowNumber: 1,
    seatNumber: 3,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 4,
    rowNumber: 1,
    seatNumber: 4,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 85,
    rowNumber: 1,
    seatNumber: 4,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 5,
    rowNumber: 1,
    seatNumber: 5,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 86,
    rowNumber: 1,
    seatNumber: 5,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 6,
    rowNumber: 1,
    seatNumber: 6,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 87,
    rowNumber: 1,
    seatNumber: 6,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 7,
    rowNumber: 1,
    seatNumber: 7,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 8,
    rowNumber: 1,
    seatNumber: 8,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 88,
    rowNumber: 2,
    seatNumber: 7,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 89,
    rowNumber: 2,
    seatNumber: 8,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 9,
    rowNumber: 2,
    seatNumber: 9,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 90,
    rowNumber: 2,
    seatNumber: 9,
    auditoriumId: 2,
    isAvailable: false,
  },
  {
    id: 10,
    rowNumber: 2,
    seatNumber: 10,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 91,
    rowNumber: 2,
    seatNumber: 10,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 11,
    rowNumber: 2,
    seatNumber: 11,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 92,
    rowNumber: 2,
    seatNumber: 11,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 12,
    rowNumber: 2,
    seatNumber: 12,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 93,
    rowNumber: 2,
    seatNumber: 12,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 13,
    rowNumber: 2,
    seatNumber: 13,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 94,
    rowNumber: 2,
    seatNumber: 13,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 14,
    rowNumber: 2,
    seatNumber: 14,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 95,
    rowNumber: 2,
    seatNumber: 14,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 15,
    rowNumber: 2,
    seatNumber: 15,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 16,
    rowNumber: 2,
    seatNumber: 16,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 17,
    rowNumber: 2,
    seatNumber: 17,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 96,
    rowNumber: 3,
    seatNumber: 15,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 97,
    rowNumber: 3,
    seatNumber: 16,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 98,
    rowNumber: 3,
    seatNumber: 17,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 18,
    rowNumber: 3,
    seatNumber: 18,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 99,
    rowNumber: 3,
    seatNumber: 18,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 19,
    rowNumber: 3,
    seatNumber: 19,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 100,
    rowNumber: 3,
    seatNumber: 19,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 20,
    rowNumber: 3,
    seatNumber: 20,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 101,
    rowNumber: 3,
    seatNumber: 20,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 21,
    rowNumber: 3,
    seatNumber: 21,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 102,
    rowNumber: 3,
    seatNumber: 21,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 22,
    rowNumber: 3,
    seatNumber: 22,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 103,
    rowNumber: 3,
    seatNumber: 22,
    auditoriumId: 2,
    isAvailable: false,
  },
  {
    id: 23,
    rowNumber: 3,
    seatNumber: 23,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 104,
    rowNumber: 3,
    seatNumber: 23,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 24,
    rowNumber: 3,
    seatNumber: 24,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 25,
    rowNumber: 3,
    seatNumber: 25,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 26,
    rowNumber: 3,
    seatNumber: 26,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 27,
    rowNumber: 3,
    seatNumber: 27,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 105,
    rowNumber: 4,
    seatNumber: 24,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 106,
    rowNumber: 4,
    seatNumber: 25,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 107,
    rowNumber: 4,
    seatNumber: 26,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 108,
    rowNumber: 4,
    seatNumber: 27,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 28,
    rowNumber: 4,
    seatNumber: 28,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 109,
    rowNumber: 4,
    seatNumber: 28,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 29,
    rowNumber: 4,
    seatNumber: 29,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 110,
    rowNumber: 4,
    seatNumber: 29,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 30,
    rowNumber: 4,
    seatNumber: 30,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 111,
    rowNumber: 4,
    seatNumber: 30,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 31,
    rowNumber: 4,
    seatNumber: 31,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 112,
    rowNumber: 4,
    seatNumber: 31,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 32,
    rowNumber: 4,
    seatNumber: 32,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 113,
    rowNumber: 4,
    seatNumber: 32,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 33,
    rowNumber: 4,
    seatNumber: 33,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 114,
    rowNumber: 4,
    seatNumber: 33,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 34,
    rowNumber: 4,
    seatNumber: 34,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 35,
    rowNumber: 4,
    seatNumber: 35,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 36,
    rowNumber: 4,
    seatNumber: 36,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 37,
    rowNumber: 4,
    seatNumber: 37,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 115,
    rowNumber: 5,
    seatNumber: 34,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 116,
    rowNumber: 5,
    seatNumber: 35,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 117,
    rowNumber: 5,
    seatNumber: 36,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 118,
    rowNumber: 5,
    seatNumber: 37,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 38,
    rowNumber: 5,
    seatNumber: 38,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 119,
    rowNumber: 5,
    seatNumber: 38,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 39,
    rowNumber: 5,
    seatNumber: 39,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 120,
    rowNumber: 5,
    seatNumber: 39,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 40,
    rowNumber: 5,
    seatNumber: 40,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 121,
    rowNumber: 5,
    seatNumber: 40,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 41,
    rowNumber: 5,
    seatNumber: 41,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 122,
    rowNumber: 5,
    seatNumber: 41,
    auditoriumId: 2,
    isAvailable: false,
  },
  {
    id: 42,
    rowNumber: 5,
    seatNumber: 42,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 123,
    rowNumber: 5,
    seatNumber: 42,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 43,
    rowNumber: 5,
    seatNumber: 43,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 124,
    rowNumber: 5,
    seatNumber: 43,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 44,
    rowNumber: 5,
    seatNumber: 44,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 45,
    rowNumber: 5,
    seatNumber: 45,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 46,
    rowNumber: 5,
    seatNumber: 46,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 47,
    rowNumber: 5,
    seatNumber: 47,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 125,
    rowNumber: 6,
    seatNumber: 44,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 126,
    rowNumber: 6,
    seatNumber: 45,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 127,
    rowNumber: 6,
    seatNumber: 46,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 128,
    rowNumber: 6,
    seatNumber: 47,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 48,
    rowNumber: 6,
    seatNumber: 48,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 129,
    rowNumber: 6,
    seatNumber: 48,
    auditoriumId: 2,
    isAvailable: false,
  },
  {
    id: 49,
    rowNumber: 6,
    seatNumber: 49,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 130,
    rowNumber: 6,
    seatNumber: 49,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 50,
    rowNumber: 6,
    seatNumber: 50,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 131,
    rowNumber: 6,
    seatNumber: 50,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 51,
    rowNumber: 6,
    seatNumber: 51,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 132,
    rowNumber: 6,
    seatNumber: 51,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 52,
    rowNumber: 6,
    seatNumber: 52,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 133,
    rowNumber: 6,
    seatNumber: 52,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 53,
    rowNumber: 6,
    seatNumber: 53,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 134,
    rowNumber: 6,
    seatNumber: 53,
    auditoriumId: 2,
    isAvailable: false,
  },
  {
    id: 54,
    rowNumber: 6,
    seatNumber: 54,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 135,
    rowNumber: 6,
    seatNumber: 54,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 55,
    rowNumber: 6,
    seatNumber: 55,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 136,
    rowNumber: 6,
    seatNumber: 55,
    auditoriumId: 2,
    isAvailable: true,
  },
  {
    id: 56,
    rowNumber: 6,
    seatNumber: 56,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 57,
    rowNumber: 6,
    seatNumber: 57,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 58,
    rowNumber: 7,
    seatNumber: 58,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 59,
    rowNumber: 7,
    seatNumber: 59,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 60,
    rowNumber: 7,
    seatNumber: 60,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 61,
    rowNumber: 7,
    seatNumber: 61,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 62,
    rowNumber: 7,
    seatNumber: 62,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 63,
    rowNumber: 7,
    seatNumber: 63,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 64,
    rowNumber: 7,
    seatNumber: 64,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 65,
    rowNumber: 7,
    seatNumber: 65,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 66,
    rowNumber: 7,
    seatNumber: 66,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 67,
    rowNumber: 7,
    seatNumber: 67,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 68,
    rowNumber: 7,
    seatNumber: 68,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 69,
    rowNumber: 7,
    seatNumber: 69,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 70,
    rowNumber: 8,
    seatNumber: 70,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 71,
    rowNumber: 8,
    seatNumber: 71,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 72,
    rowNumber: 8,
    seatNumber: 72,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 73,
    rowNumber: 8,
    seatNumber: 73,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 74,
    rowNumber: 8,
    seatNumber: 74,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 75,
    rowNumber: 8,
    seatNumber: 75,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 76,
    rowNumber: 8,
    seatNumber: 76,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 77,
    rowNumber: 8,
    seatNumber: 77,
    auditoriumId: 1,
    isAvailable: false,
  },
  {
    id: 78,
    rowNumber: 8,
    seatNumber: 78,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 79,
    rowNumber: 8,
    seatNumber: 79,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 80,
    rowNumber: 8,
    seatNumber: 80,
    auditoriumId: 1,
    isAvailable: true,
  },
  {
    id: 81,
    rowNumber: 8,
    seatNumber: 81,
    auditoriumId: 1,
    isAvailable: true,
  },
];
